import type { Metadata } from "next";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import RadixProdivder from "@/contexts/radix-prodivder";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-yellow/20 w-screen h-screen">
        <RadixProdivder>{children}</RadixProdivder>
      </body>
    </html>
  );
}
